---
title: Bloku catch nebylo nikdy dosaženo; <exception>zpracované výše ve stejném příkazu try
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 987a509b4b099a0a1f728f55dfb2b35a8770af3f
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 06/04/2020
ms.locfileid: "84395477"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>Bloku catch nebylo nikdy dosaženo; \<exception>zpracované výše ve stejném příkazu try
`Catch`Blok v kódu není dostupný, protože se zpracovává v předchozím `Try` bloku.  
  
Ve výchozím nastavení je tato zpráva upozornění. Další informace o skrývání upozornění nebo zpracování upozornění jako chyb najdete v tématu [Konfigurace upozornění v Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **ID chyby:** BC42031  
  
## <a name="to-correct-this-error"></a>Oprava této chyby  
  
- Odeberte redundantní příkaz.  
  
## <a name="see-also"></a>Viz také

- [Jak zachytit výjimky pomocí bloku try/catch](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Používání obslužných rutin uživatelsky filtrovaných výjimek](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try...Catch....Finally – příkaz](../language-reference/statements/try-catch-finally-statement.md)
