---
title: Výjimky a zpracování výjimek – průvodce programováním jazyka C#
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: b883012cf8f72247ff4e0b47a46eee1854e2d534
ms.sourcegitcommit: 7588136e355e10cbc2582f389c90c127363c02a5
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 03/15/2020
ms.locfileid: "76735658"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="4d6b5-102">Výjimky a jejich zpracování (Průvodce programováním v C#)</span><span class="sxs-lookup"><span data-stu-id="4d6b5-102">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="4d6b5-103">Funkce zpracování výjimek jazyka C# vám pomohou řešit všechny neočekávané nebo výjimečné situace, ke kterým dochází při spuštění programu.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-103">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="4d6b5-104">Zpracování výjimek `try` `catch`používá `finally` , a klíčová slova vyzkoušet akce, které nemusí být úspěšné, ke zpracování selhání, když se rozhodnete, že je rozumné tak učinit, a vyčistit prostředky později.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-104">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it is reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="4d6b5-105">Výjimky mohou být generovány cltime jazyka common jazyk (CLR), rozhraním .NET Framework nebo knihovnami třetích stran nebo kódem aplikace.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-105">Exceptions can be generated by the common language runtime (CLR), by the .NET Framework or any third-party libraries, or by application code.</span></span> <span data-ttu-id="4d6b5-106">Výjimky jsou vytvářeny `throw` pomocí klíčového slova.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-106">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="4d6b5-107">V mnoha případech může být vyvolána výjimka není metodou, která váš kód volá přímo, ale jinou metodou dále v zásobníku volání.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-107">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="4d6b5-108">V takovém případě CLR unwind zásobníku, hledá metodu s blokem `catch` pro konkrétní typ výjimky a provede první takový `catch` blok, který pokud najde.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-108">When this happens, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="4d6b5-109">Pokud najde žádný `catch` vhodný blok kdekoli v zásobníku volání, ukončí proces a zobrazí zprávu uživateli.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-109">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="4d6b5-110">V tomto příkladu metoda testuje dělení nulou a zachytí chybu.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-110">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="4d6b5-111">Bez zpracování výjimky by tento program ukončen s **DivideByZeroException byla neošetřená** chyba.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-111">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

[!code-csharp[csProgGuideExceptions#18](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#18)]

## <a name="exceptions-overview"></a><span data-ttu-id="4d6b5-112">Přehled výjimek</span><span class="sxs-lookup"><span data-stu-id="4d6b5-112">Exceptions Overview</span></span>

<span data-ttu-id="4d6b5-113">Výjimky mají následující vlastnosti:</span><span class="sxs-lookup"><span data-stu-id="4d6b5-113">Exceptions have the following properties:</span></span>

- <span data-ttu-id="4d6b5-114">Výjimky jsou typy, které `System.Exception`všechny nakonec pocházejí z .</span><span class="sxs-lookup"><span data-stu-id="4d6b5-114">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="4d6b5-115">Použijte `try` blok kolem příkazy, které mohou vyvolat výjimky.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-115">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="4d6b5-116">Jakmile dojde k výjimce v `try` bloku, tok řízení přeskočí na první přidruženou obslužnou rutinu výjimky, která je k dispozici kdekoli v zásobníku volání.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-116">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="4d6b5-117">V c# `catch` klíčové slovo se používá k definování obslužné rutiny výjimky.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-117">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="4d6b5-118">Pokud není k dispozici žádná obslužná rutina výjimky pro danou výjimku, program přestane provádět s chybovou zprávou.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-118">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="4d6b5-119">Nezachyťte výjimku, pokud ji nemůžete zpracovat a ponechat aplikaci ve známém stavu.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-119">Do not catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="4d6b5-120">Pokud chytíte `System.Exception`, re-throw `throw` pomocí klíčového `catch` slova na konci bloku.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-120">If you catch `System.Exception`, re-throw it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="4d6b5-121">Pokud `catch` blok definuje proměnnou výjimky, můžete ji použít k získání dalších informací o typu výjimky, ke které došlo.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-121">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="4d6b5-122">Výjimky mohou být explicitně generovány `throw` programem pomocí klíčového slova.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-122">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="4d6b5-123">Objekty výjimek obsahují podrobné informace o chybě, jako je například stav zásobníku volání a textový popis chyby.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-123">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="4d6b5-124">Kód v `finally` bloku je spuštěn i v případě, že je vyvolána výjimka.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-124">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="4d6b5-125">Pomocí `finally` bloku uvolněte prostředky, například zavřete všechny datové `try` proudy nebo soubory, které byly otevřeny v bloku.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-125">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="4d6b5-126">Spravované výjimky v rozhraní .NET Framework jsou implementovány nad mechanismus zpracování strukturovaných výjimek Win32.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-126">Managed exceptions in the .NET Framework are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="4d6b5-127">Další informace naleznete [v tématech Strukturované zpracování výjimek (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) a [Crash Course na hloubkách win32 strukturované zpracování výjimek](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span><span class="sxs-lookup"><span data-stu-id="4d6b5-127">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="related-sections"></a><span data-ttu-id="4d6b5-128">Související oddíly</span><span class="sxs-lookup"><span data-stu-id="4d6b5-128">Related Sections</span></span>

<span data-ttu-id="4d6b5-129">Další informace o výjimkách a zpracování výjimek naleznete v následujících článcích:</span><span class="sxs-lookup"><span data-stu-id="4d6b5-129">See the following articles for more information about exceptions and exception handling:</span></span>

- [<span data-ttu-id="4d6b5-130">Použití výjimek</span><span class="sxs-lookup"><span data-stu-id="4d6b5-130">Using Exceptions</span></span>](using-exceptions.md)
- [<span data-ttu-id="4d6b5-131">Zpracování výjimek</span><span class="sxs-lookup"><span data-stu-id="4d6b5-131">Exception Handling</span></span>](exception-handling.md)
- [<span data-ttu-id="4d6b5-132">Vytváření a vyvolávání výjimek</span><span class="sxs-lookup"><span data-stu-id="4d6b5-132">Creating and Throwing Exceptions</span></span>](creating-and-throwing-exceptions.md)
- [<span data-ttu-id="4d6b5-133">Výjimky generované kompilátorem</span><span class="sxs-lookup"><span data-stu-id="4d6b5-133">Compiler-Generated Exceptions</span></span>](compiler-generated-exceptions.md)
- [<span data-ttu-id="4d6b5-134">Jak zpracovat výjimku pomocí try/catch (Průvodce programováním jazyka C#)</span><span class="sxs-lookup"><span data-stu-id="4d6b5-134">How to handle an exception using try/catch (C# Programming Guide)</span></span>](how-to-handle-an-exception-using-try-catch.md)
- [<span data-ttu-id="4d6b5-135">Jak provést vyčištění kódu pomocí příkazu finally</span><span class="sxs-lookup"><span data-stu-id="4d6b5-135">How to execute cleanup code using finally</span></span>](how-to-execute-cleanup-code-using-finally.md)
- [<span data-ttu-id="4d6b5-136">Jak zachytit výjimku nekompatibilní se specifikací CLS</span><span class="sxs-lookup"><span data-stu-id="4d6b5-136">How to catch a non-CLS exception</span></span>](how-to-catch-a-non-cls-exception.md)

## <a name="c-language-specification"></a><span data-ttu-id="4d6b5-137">Specifikace jazyka C#</span><span class="sxs-lookup"><span data-stu-id="4d6b5-137">C# Language Specification</span></span>

<span data-ttu-id="4d6b5-138">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span><span class="sxs-lookup"><span data-stu-id="4d6b5-138">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="4d6b5-139">Specifikace jazyka je úplným a rozhodujícím zdrojem pro syntaxi a použití jazyka C#.</span><span class="sxs-lookup"><span data-stu-id="4d6b5-139">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="4d6b5-140">Viz také</span><span class="sxs-lookup"><span data-stu-id="4d6b5-140">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="4d6b5-141">Programovací příručka jazyka C#</span><span class="sxs-lookup"><span data-stu-id="4d6b5-141">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="4d6b5-142">C# Klíčová slova</span><span class="sxs-lookup"><span data-stu-id="4d6b5-142">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="4d6b5-143">throw</span><span class="sxs-lookup"><span data-stu-id="4d6b5-143">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="4d6b5-144">try-catch</span><span class="sxs-lookup"><span data-stu-id="4d6b5-144">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="4d6b5-145">try-finally</span><span class="sxs-lookup"><span data-stu-id="4d6b5-145">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="4d6b5-146">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="4d6b5-146">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="4d6b5-147">Výjimky</span><span class="sxs-lookup"><span data-stu-id="4d6b5-147">Exceptions</span></span>](../../../standard/exceptions/index.md)
